#!/usr/bin/env node
/*▄────────────────────▄
  █                    █
  █  Загрузка модулей  █
  █                    █
  ▀────────────────────▀*/
require('.'); // Работа с MVC-моделью

/*▄───────▄
  █       █
  █  MVC  █
  █       █
  ▀───────▀*/
// Коллекция точек входа
require('./app/entrypoints/entrypointInstall');

/*▄───────────────▄
  █               █
  █  Точка входа  █
  █               █
  ▀───────────────▀*/
entrypoint = (...args) => {
    if (args[0] == 'i') {
        $.entrypoint.Install(...args.slice(1))
    }
};
